import { hashPassword } from './auth.ts';
import { ALL_INDIAN_STATES, STATE_RECRUITMENT_ORGS } from './data/statesList.ts';
import { ALL_STATE_GOVERNMENT_JOBS } from './data/stateGovtJobs.ts';
import { ALL_STATE_PRIVATE_JOBS } from './data/statePrivateJobs.ts';
import { INITIAL_CAREER_ROADMAPS } from './data/careerRoadmapsData.ts';
import { INITIAL_GOVERNMENT_EXAMS, INITIAL_PRACTICE_QUESTIONS, INITIAL_MOCK_TESTS } from './data/examPrepData.ts';
import {
  User,
  StudentProfile,
  StateEntity,
  SectorEntity,
  Organization,
  Department,
  Examination,
  ExamGroup,
  PostService,
  Job,
  ExamPattern,
  ExamPatternColumn,
  ExamPatternRow,
  ExamPatternCell,
  SyllabusSubject,
  SyllabusTopic,
  SyllabusSubtopic,
  PreparationRoadmapPhase,
  Notice,
  Announcement,
  Notification,
} from './types.ts';

export function getInitialSeedData() {
  // Admin user: Viksit Coders / SSLKHR
  const adminAuth = hashPassword('SSLKHR');
  const studentAuth = hashPassword('student123');

  const users: User[] = [
    {
      id: 'usr_admin_01',
      email: 'admin@careerdefiner.gov.in',
      username: 'Viksit Coders',
      passwordHash: adminAuth.hash,
      salt: adminAuth.salt,
      fullName: 'Viksit Coders',
      mobileNumber: '+91 9876543210',
      role: 'ADMIN',
      isActive: true,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'usr_student_01',
      email: 'student@example.com',
      passwordHash: studentAuth.hash,
      salt: studentAuth.salt,
      fullName: 'Sai Teja',
      mobileNumber: '+91 9123456789',
      role: 'STUDENT',
      isActive: true,
      createdAt: '2026-02-01T00:00:00.000Z',
      updatedAt: '2026-02-01T00:00:00.000Z',
    },
  ];

  const studentProfiles: StudentProfile[] = [
    {
      id: 'prof_student_01',
      userId: 'usr_student_01',
      fullName: 'Sai Teja',
      email: 'student@example.com',
      mobileNumber: '+91 9123456789',
      dateOfBirth: '2001-06-15',
      gender: 'Male',
      state: 'Andhra Pradesh',
      district: 'Visakhapatnam',
      highestQualification: 'B.Tech',
      courseDegree: 'B.Tech Computer Science and Engineering',
      branchStream: 'Computer Science',
      institution: 'Andhra University College of Engineering',
      passingYear: 2023,
      percentageCgpa: '8.4 CGPA',
      interests: ['Government Jobs', 'IT', 'Banking', 'Police'],
      skills: ['Quantitative Aptitude', 'Reasoning', 'Python', 'General Studies', 'Problem Solving'],
      preferredSector: 'Government',
      preferredJobType: 'Full-Time',
      preferredLocation: 'Andhra Pradesh, Telangana, New Delhi',
      preferredCategories: ['CENTRAL', 'STATE'],
      createdAt: '2026-02-01T00:00:00.000Z',
      updatedAt: '2026-02-01T00:00:00.000Z',
    },
  ];

  const states: StateEntity[] = ALL_INDIAN_STATES;

  const sectors: SectorEntity[] = [
    { id: 'sec_civil', name: 'Civil Services & Public Administration', code: 'CIVIL', description: 'Premier administrative, executive, and foreign services' },
    { id: 'sec_defence', name: 'Defence & Armed Forces', code: 'DEFENCE', description: 'Army, Navy, Air Force, Coast Guard and Paramilitary' },
    { id: 'sec_railways', name: 'Railways & Transport', code: 'RAILWAYS', description: 'Indian Railways technical, non-technical, and executive posts' },
    { id: 'sec_banking', name: 'Banking & Financial Institutions', code: 'BANKING', description: 'Public Sector Banks, Reserve Bank of India, and NABARD' },
    { id: 'sec_police', name: 'Police & Law Enforcement', code: 'POLICE', description: 'State and Central armed police forces, investigation bureaus' },
    { id: 'sec_engineering', name: 'Technical & Engineering Services', code: 'ENGG', description: 'Engineering services, research bodies, scientific recruitment' },
    { id: 'sec_teaching', name: 'Education & Academic Services', code: 'TEACHING', description: 'School education, colleges, and university commissions' },
    { id: 'sec_it', name: 'Information Technology & Software', code: 'IT', description: 'Software engineering, data science, cybersecurity, and cloud' },
  ];

  const organizations: Organization[] = [
    // Central
    {
      id: 'org_upsc',
      name: 'Union Public Service Commission',
      shortName: 'UPSC',
      type: 'CENTRAL',
      sectorId: 'sec_civil',
      description: 'The premier central recruiting agency of the Government of India for recruitment of all Group A officers.',
      officialWebsite: 'https://upsc.gov.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'org_ssc',
      name: 'Staff Selection Commission',
      shortName: 'SSC',
      type: 'CENTRAL',
      sectorId: 'sec_civil',
      description: 'An attached office of the Department of Personnel and Training (DoPT) recruiting staff for various ministries.',
      officialWebsite: 'https://ssc.gov.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'org_rrb',
      name: 'Railway Recruitment Control Board',
      shortName: 'RRB / Indian Railways',
      type: 'CENTRAL',
      sectorId: 'sec_railways',
      description: 'Government body responsible for recruiting staff for Indian Railways across various technical and non-technical zones.',
      officialWebsite: 'https://indianrailways.gov.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'org_ibps',
      name: 'Institute of Banking Personnel Selection',
      shortName: 'IBPS',
      type: 'CENTRAL',
      sectorId: 'sec_banking',
      description: 'Autonomous agency that conducts competitive exams for recruitment of clerks and officers in public sector banks.',
      officialWebsite: 'https://ibps.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'org_defence',
      name: 'Ministry of Defence (Indian Armed Forces)',
      shortName: 'Defence / UPSC CDS & NDA',
      type: 'CENTRAL',
      sectorId: 'sec_defence',
      description: 'The armed forces of the Republic of India consisting of Army, Navy, and Air Force.',
      officialWebsite: 'https://joinindianarmy.nic.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },

    // State - Andhra Pradesh
    {
      id: 'org_appsc',
      name: 'Andhra Pradesh Public Service Commission',
      shortName: 'APPSC',
      type: 'STATE',
      stateId: 'st_ap',
      sectorId: 'sec_civil',
      description: 'State recruitment commission constituted under the Constitution of India for the state of Andhra Pradesh.',
      officialWebsite: 'https://psc.ap.gov.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'org_appolice',
      name: 'Andhra Pradesh State Level Police Recruitment Board',
      shortName: 'AP Police Board',
      type: 'STATE',
      stateId: 'st_ap',
      sectorId: 'sec_police',
      description: 'Nodal agency for recruitment of Sub-Inspectors, Constables and specialized police personnel in Andhra Pradesh.',
      officialWebsite: 'https://slprb.ap.gov.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },

    // State - Telangana
    {
      id: 'org_tspsc',
      name: 'Telangana State Public Service Commission',
      shortName: 'TSPSC',
      type: 'STATE',
      stateId: 'st_tg',
      sectorId: 'sec_civil',
      description: 'Constitutional recruitment commission selecting staff for government posts in Telangana.',
      officialWebsite: 'https://tspsc.gov.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },

    // Private Sector Organizations
    {
      id: 'org_tech_tcs',
      name: 'Tata Consultancy Services',
      shortName: 'TCS',
      type: 'PRIVATE',
      sectorId: 'sec_it',
      description: 'Leading global IT services, consulting, and business solutions organization headquartered in Mumbai.',
      officialWebsite: 'https://tcs.com/careers',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'org_hdfc_bank',
      name: 'HDFC Bank Limited',
      shortName: 'HDFC Bank',
      type: 'PRIVATE',
      sectorId: 'sec_banking',
      description: 'Leading Indian banking and financial services company headquartered in Mumbai.',
      officialWebsite: 'https://www.hdfcbank.com/careers',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    ...STATE_RECRUITMENT_ORGS,
  ];

  const departments: Department[] = [
    { id: 'dept_rev', organizationId: 'org_appsc', name: 'Revenue Department', description: 'Land records, survey, and district civil administration' },
    { id: 'dept_home', organizationId: 'org_appsc', name: 'Home Department', description: 'Internal security and police executive services' },
    { id: 'dept_panchayat', organizationId: 'org_appsc', name: 'Panchayat Raj & Rural Development', description: 'Rural governance, infrastructure and welfare schemes' },
    { id: 'dept_dopt', organizationId: 'org_upsc', name: 'Department of Personnel and Training (DoPT)', description: 'Nodal department for personnel management' },
    { id: 'dept_cbic', organizationId: 'org_ssc', name: 'Central Board of Indirect Taxes & Customs (CBIC)', description: 'GST and customs administration' },
  ];

  const examinations: Examination[] = [
    // UPSC Exams
    {
      id: 'exam_upsc_cse',
      name: 'Civil Services Examination',
      shortName: 'UPSC CSE',
      organizationId: 'org_upsc',
      examType: 'National',
      qualification: 'Graduation',
      description: 'The premier national competitive examination conducted by UPSC for recruitment to higher civil services including IAS, IPS, IFS, and IRS.',
      minAge: 21,
      maxAge: 32,
      selectionProcess: 'Preliminary Examination (Objective) -> Main Examination (Written Descriptive) -> Personality Test (Interview)',
      officialNotificationUrl: 'https://upsc.gov.in/examinations/active-exams',
      officialWebsiteUrl: 'https://upsc.gov.in',
      officialApplicationUrl: 'https://upsconline.nic.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'exam_upsc_ese',
      name: 'Engineering Services Examination',
      shortName: 'UPSC ESE / IES',
      organizationId: 'org_upsc',
      examType: 'National',
      qualification: 'B.Tech',
      description: 'Recruitment examination to fill engineer posts in Civil, Mechanical, Electrical, and Electronics & Telecom engineering cadres of the Central Government.',
      minAge: 21,
      maxAge: 30,
      selectionProcess: 'Stage-I Preliminary -> Stage-II Mains Descriptive -> Stage-III Personality Test',
      officialNotificationUrl: 'https://upsc.gov.in',
      officialWebsiteUrl: 'https://upsc.gov.in',
      officialApplicationUrl: 'https://upsconline.nic.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },

    // SSC Exams
    {
      id: 'exam_ssc_cgl',
      name: 'Combined Graduate Level Examination',
      shortName: 'SSC CGL',
      organizationId: 'org_ssc',
      examType: 'National',
      qualification: 'Graduation',
      description: 'Recruitment examination conducted to recruit staff for Group B and C non-technical posts across ministries, departments, and attached offices.',
      minAge: 18,
      maxAge: 32,
      selectionProcess: 'Computer Based Examination Tier-I (Qualifying) -> Tier-II (Merit & Computer Module) -> Document Verification',
      officialNotificationUrl: 'https://ssc.gov.in',
      officialWebsiteUrl: 'https://ssc.gov.in',
      officialApplicationUrl: 'https://ssc.gov.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'exam_ssc_chsl',
      name: 'Combined Higher Secondary (10+2) Level Examination',
      shortName: 'SSC CHSL',
      organizationId: 'org_ssc',
      examType: 'National',
      qualification: '12th',
      description: 'Recruitment examination for candidates possessing 12th standard qualification for Lower Division Clerks, Junior Secretariat Assistants, and Data Entry Operators.',
      minAge: 18,
      maxAge: 27,
      selectionProcess: 'Tier-I (CBT) -> Tier-II (CBT & Skill/Typing Test)',
      officialNotificationUrl: 'https://ssc.gov.in',
      officialWebsiteUrl: 'https://ssc.gov.in',
      officialApplicationUrl: 'https://ssc.gov.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },

    // Railways
    {
      id: 'exam_rrb_ntpc',
      name: 'Non-Technical Popular Categories (NTPC)',
      shortName: 'RRB NTPC',
      organizationId: 'org_rrb',
      examType: 'National',
      qualification: 'Graduation',
      description: 'Recruitment for commercial apprentices, station masters, goods guards, and senior clerks across Zonal Railways.',
      minAge: 18,
      maxAge: 33,
      selectionProcess: '1st Stage CBT -> 2nd Stage CBT -> Computer Based Aptitude Test (CBAT) / Typing Skill Test -> Document Verification & Medical',
      officialNotificationUrl: 'https://indianrailways.gov.in',
      officialWebsiteUrl: 'https://indianrailways.gov.in',
      officialApplicationUrl: 'https://indianrailways.gov.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },

    // Banking
    {
      id: 'exam_ibps_po',
      name: 'Common Recruitment Process for Probationary Officers (CRP PO/MT)',
      shortName: 'IBPS PO',
      organizationId: 'org_ibps',
      examType: 'National',
      qualification: 'Graduation',
      description: 'Competitive entrance examination for selecting Probationary Officers and Management Trainees in 11 participating public sector banks.',
      minAge: 20,
      maxAge: 30,
      selectionProcess: 'Online Preliminary Examination -> Online Main Examination -> Common Interview',
      officialNotificationUrl: 'https://ibps.in',
      officialWebsiteUrl: 'https://ibps.in',
      officialApplicationUrl: 'https://ibps.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },

    // State - APPSC
    {
      id: 'exam_appsc_grp1',
      name: 'Group-I Services Examination',
      shortName: 'APPSC Group-I',
      organizationId: 'org_appsc',
      examType: 'State',
      qualification: 'Graduation',
      description: 'Premier civil administrative examination of Andhra Pradesh selecting Deputy Collectors, DSPs, CTOs and District Officers.',
      minAge: 18,
      maxAge: 42,
      selectionProcess: 'Preliminary Screening Test (Objective) -> Written Examination Mains (Descriptive Conventional) -> Oral Test (Interview)',
      officialNotificationUrl: 'https://psc.ap.gov.in',
      officialWebsiteUrl: 'https://psc.ap.gov.in',
      officialApplicationUrl: 'https://psc.ap.gov.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'exam_appsc_grp2',
      name: 'Group-II Services Examination',
      shortName: 'APPSC Group-II',
      organizationId: 'org_appsc',
      examType: 'State',
      qualification: 'Graduation',
      description: 'Executive and Non-Executive posts in Andhra Pradesh State Secretariat and subordinate departments (Municipal Commissioners, Sub-Registrars, ASO).',
      minAge: 18,
      maxAge: 42,
      selectionProcess: 'Preliminary Screening Test (CBT/OMR) -> Mains Examination (Objective CBT) -> Computer Proficiency Test',
      officialNotificationUrl: 'https://psc.ap.gov.in',
      officialWebsiteUrl: 'https://psc.ap.gov.in',
      officialApplicationUrl: 'https://psc.ap.gov.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'exam_appolice_si',
      name: 'SCT Sub-Inspectors of Police (Civil & AR)',
      shortName: 'AP Police SI',
      organizationId: 'org_appolice',
      examType: 'State',
      qualification: 'Graduation',
      description: 'Stipendiary Cadet Trainee Sub-Inspectors in Police, Special Police, and Station Fire Officers recruitment.',
      minAge: 21,
      maxAge: 27,
      selectionProcess: 'Preliminary Written Test -> Physical Measurement Test (PMT) & Physical Efficiency Test (PET) -> Final Written Examination',
      officialNotificationUrl: 'https://slprb.ap.gov.in',
      officialWebsiteUrl: 'https://slprb.ap.gov.in',
      officialApplicationUrl: 'https://slprb.ap.gov.in',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ];

  const examGroups: ExamGroup[] = [
    {
      id: 'grp_appsc_1',
      examinationId: 'exam_appsc_grp1',
      name: 'Group-I',
      description: 'State Executive & Administrative Cadres (Deputy Collector, DSP, CTO, DFO, Municipal Commissioner Gr.I)',
      displayOrder: 1,
      status: 'PUBLISHED',
    },
    {
      id: 'grp_appsc_2',
      examinationId: 'exam_appsc_grp2',
      name: 'Group-II',
      description: 'Executive Posts (Sub-Registrar, Municipal Commissioner Gr.III, ACTO) and Non-Executive Posts (ASO, Senior Auditor)',
      displayOrder: 2,
      status: 'PUBLISHED',
    },
    {
      id: 'grp_ssc_cgl_b',
      examinationId: 'exam_ssc_cgl',
      name: 'Group B (Gazetted & Non-Gazetted)',
      description: 'Assistant Section Officer, Inspector Central Excise, Assistant Enforcement Officer',
      displayOrder: 1,
      status: 'PUBLISHED',
    },
    {
      id: 'grp_ssc_cgl_c',
      examinationId: 'exam_ssc_cgl',
      name: 'Group C',
      description: 'Tax Assistant, Auditor, Accountant, Junior Accountant',
      displayOrder: 2,
      status: 'PUBLISHED',
    },
  ];

  const postsServices: PostService[] = [
    // Under UPSC Civil Services
    {
      id: 'post_ias',
      name: 'Indian Administrative Service (IAS)',
      organizationId: 'org_upsc',
      examinationId: 'exam_upsc_cse',
      description: 'The premier administrative arm of the All India Services responsible for policy formulation, execution, and district magistracy.',
      qualification: 'Graduation',
      minAge: 21,
      maxAge: 32,
      paySalary: 'Level 10 (₹56,100 to ₹2,50,000 Cabinet Secretary)',
      responsibilities: 'District Administration, Policy Implementation, Law & Order Coordination, Public Welfare Execution',
      careerGrowth: 'Sub-Divisional Magistrate (SDM) -> District Magistrate / Collector -> Joint Secretary -> Secretary to Government of India',
      officialSourceUrl: 'https://dopt.gov.in',
      status: 'PUBLISHED',
    },
    {
      id: 'post_ips',
      name: 'Indian Police Service (IPS)',
      organizationId: 'org_upsc',
      examinationId: 'exam_upsc_cse',
      description: 'Leading law enforcement leadership agency in India supervising state police apparatus, intelligence, and border security.',
      qualification: 'Graduation',
      minAge: 21,
      maxAge: 32,
      paySalary: 'Level 10 (₹56,100 to ₹2,25,000 DGP)',
      responsibilities: 'Crime Prevention, Investigation, Public Order, Intelligence, Border & Security Management',
      careerGrowth: 'Assistant Superintendent of Police (ASP) -> Superintendent of Police (SP) -> DIG -> IG -> Director General of Police (DGP)',
      officialSourceUrl: 'https://mha.gov.in',
      status: 'PUBLISHED',
    },
    {
      id: 'post_ifs',
      name: 'Indian Foreign Service (IFS)',
      organizationId: 'org_upsc',
      examinationId: 'exam_upsc_cse',
      description: 'Diplomatic service of India representing the nation in foreign missions, embassies, and international multilateral organizations.',
      qualification: 'Graduation',
      minAge: 21,
      maxAge: 32,
      paySalary: 'Level 10 + Foreign Allowance',
      responsibilities: 'Diplomacy, Bilateral Negotiations, Trade Partnerships, Protection of Indian Citizens Overseas',
      careerGrowth: 'Third Secretary -> Second Secretary -> First Secretary -> Counsellor -> Ambassador / High Commissioner',
      officialSourceUrl: 'https://mea.gov.in',
      status: 'PUBLISHED',
    },
    {
      id: 'post_irs',
      name: 'Indian Revenue Service (IRS - IT & Customs)',
      organizationId: 'org_upsc',
      examinationId: 'exam_upsc_cse',
      description: 'Central civil service responsible for direct tax collection (CBDT) and indirect tax/customs administration (CBIC).',
      qualification: 'Graduation',
      minAge: 21,
      maxAge: 32,
      paySalary: 'Level 10 (₹56,100 to ₹2,25,000 Principal Chief Commissioner)',
      responsibilities: 'Tax Assessment, Anti-Evasion, Financial Intelligence, Customs & Port Clearances',
      careerGrowth: 'Assistant Commissioner -> Deputy Commissioner -> Joint Commissioner -> Commissioner -> Principal Chief Commissioner',
      officialSourceUrl: 'https://incometaxindia.gov.in',
      status: 'PUBLISHED',
    },

    // Under SSC CGL
    {
      id: 'post_ssc_aso',
      name: 'Assistant Section Officer (ASO)',
      organizationId: 'org_ssc',
      examinationId: 'exam_ssc_cgl',
      groupId: 'grp_ssc_cgl_b',
      description: 'Key desk officer responsible for policy note drafting, file routing, and departmental governance in Central Secretariat Service (CSS).',
      qualification: 'Graduation',
      minAge: 20,
      maxAge: 30,
      paySalary: 'Level 7 (₹44,900 to ₹1,42,400)',
      responsibilities: 'Secretariat Noting, Case Preparation, Parliamentary Questions drafting',
      careerGrowth: 'ASO -> Section Officer -> Under Secretary -> Deputy Secretary',
      officialSourceUrl: 'https://dopt.gov.in',
      status: 'PUBLISHED',
    },
    {
      id: 'post_ssc_excise',
      name: 'Inspector (Central Excise & GST)',
      organizationId: 'org_ssc',
      examinationId: 'exam_ssc_cgl',
      groupId: 'grp_ssc_cgl_b',
      description: 'Executive field officer inspecting commercial accounts, executing anti-evasion raids, and enforcing Goods & Services Tax.',
      qualification: 'Graduation',
      minAge: 18,
      maxAge: 30,
      paySalary: 'Level 7 (₹44,900 to ₹1,42,400)',
      responsibilities: 'GST Audits, Factory Verifications, Intelligence Gatherings, Enforcement',
      careerGrowth: 'Inspector -> Superintendent -> Assistant Commissioner',
      officialSourceUrl: 'https://cbic.gov.in',
      status: 'PUBLISHED',
    },

    // Under APPSC Group-I
    {
      id: 'post_appsc_dep_collector',
      name: 'Deputy Collector (Executive Branch)',
      organizationId: 'org_appsc',
      examinationId: 'exam_appsc_grp1',
      groupId: 'grp_appsc_1',
      departmentId: 'dept_rev',
      description: 'Highest state civil service executive post handling Sub-Divisional Revenue Officer (RDO) and executive magistracy duties.',
      qualification: 'Graduation',
      minAge: 18,
      maxAge: 42,
      paySalary: '₹61,960 - ₹1,51,370 (AP State Pay Matrix)',
      responsibilities: 'Revenue Courts, Land Administration, Disaster Management, Law and Order',
      careerGrowth: 'RDO / Deputy Collector -> Special Grade Deputy Collector -> Joint Collector -> Conferred IAS',
      officialSourceUrl: 'https://psc.ap.gov.in',
      status: 'PUBLISHED',
    },
    {
      id: 'post_appsc_dsp',
      name: 'Deputy Superintendent of Police (DSP - Civil)',
      organizationId: 'org_appsc',
      examinationId: 'exam_appsc_grp1',
      groupId: 'grp_appsc_1',
      departmentId: 'dept_home',
      description: 'Sub-divisional police commander leading police stations, supervising serious crime investigations and maintenance of order.',
      qualification: 'Graduation',
      minAge: 21,
      maxAge: 30,
      paySalary: '₹61,960 - ₹1,51,370 (AP State Pay Matrix)',
      responsibilities: 'Police Sub-Division Command, Crime Investigation, Security Protocol, Personnel Supervision',
      careerGrowth: 'DSP -> Additional SP -> Superintendent of Police (Non-Cadre) -> Conferred IPS',
      officialSourceUrl: 'https://slprb.ap.gov.in',
      status: 'PUBLISHED',
    },

    // Under AP Police
    {
      id: 'post_ap_si',
      name: 'Sub-Inspector of Police (Civil)',
      organizationId: 'org_appolice',
      examinationId: 'exam_appolice_si',
      departmentId: 'dept_home',
      description: 'Station House Officer (SHO) directing local police station duties, investigating cognizable offenses, and serving public safety.',
      qualification: 'Graduation',
      minAge: 21,
      maxAge: 27,
      paySalary: '₹44,570 - ₹1,27,480',
      responsibilities: 'First Information Reports (FIR), Crime Investigation, Beat Patrol, Court Evidence',
      careerGrowth: 'Sub-Inspector -> Circle Inspector -> DSP',
      officialSourceUrl: 'https://slprb.ap.gov.in',
      status: 'PUBLISHED',
    },
  ];

  const jobs: Job[] = [
    // Gov Job 1: UPSC CSE
    {
      id: 'job_upsc_cse_2026',
      title: 'Civil Services (Preliminary) Examination 2026 — IAS, IPS, IFS, IRS Recruitment',
      jobType: 'GOVERNMENT',
      category: 'CENTRAL',
      organizationId: 'org_upsc',
      examinationId: 'exam_upsc_cse',
      qualification: 'Graduation',
      branch: 'Any Discipline / All Streams',
      minAge: 21,
      maxAge: 32,
      salary: '₹56,100 - ₹2,50,000 (Pay Level 10 to 18)',
      vacancies: 1056,
      applicationStartDate: '2026-02-14',
      applicationEndDate: '2026-03-05',
      examDate: '2026-05-24',
      selectionProcess: 'Preliminary Examination (Objective) -> Main Examination (Written) -> Personality Test',
      officialNotificationUrl: 'https://upsc.gov.in/sites/default/files/Notification-CSP-2026-Engl.pdf',
      officialApplicationUrl: 'https://upsconline.nic.in',
      status: 'PUBLISHED',
      viewsCount: 1420,
      createdAt: '2026-02-14T00:00:00.000Z',
      updatedAt: '2026-02-14T00:00:00.000Z',
    },

    // Gov Job 2: SSC CGL
    {
      id: 'job_ssc_cgl_2026',
      title: 'SSC Combined Graduate Level (CGL) Examination 2026 for Group B & C Posts',
      jobType: 'GOVERNMENT',
      category: 'CENTRAL',
      organizationId: 'org_ssc',
      examinationId: 'exam_ssc_cgl',
      groupId: 'grp_ssc_cgl_b',
      qualification: 'Graduation',
      branch: 'Any Recognized Bachelor Degree',
      minAge: 18,
      maxAge: 32,
      salary: '₹25,500 - ₹1,42,400 (Level 4 to Level 8)',
      vacancies: 14582,
      applicationStartDate: '2026-06-11',
      applicationEndDate: '2026-07-10',
      examDate: '2026-09-15',
      selectionProcess: 'Computer Based Exam Tier-I -> Tier-II -> Document Verification',
      officialNotificationUrl: 'https://ssc.gov.in/portal/notices',
      officialApplicationUrl: 'https://ssc.gov.in',
      status: 'PUBLISHED',
      viewsCount: 980,
      createdAt: '2026-06-11T00:00:00.000Z',
      updatedAt: '2026-06-11T00:00:00.000Z',
    },

    // Gov Job 3: APPSC Group-I
    {
      id: 'job_appsc_grp1_2026',
      title: 'APPSC Group-I Services Recruitment Notification — Deputy Collector, DSP, CTO',
      jobType: 'GOVERNMENT',
      category: 'STATE',
      stateId: 'st_ap',
      organizationId: 'org_appsc',
      examinationId: 'exam_appsc_grp1',
      groupId: 'grp_appsc_1',
      qualification: 'Graduation',
      branch: 'Any Recognized Degree',
      minAge: 18,
      maxAge: 42,
      salary: '₹61,960 - ₹1,51,370 per month',
      vacancies: 89,
      applicationStartDate: '2026-01-10',
      applicationEndDate: '2026-01-31',
      examDate: '2026-04-19',
      selectionProcess: 'Screening Test (Objective) -> Conventional Mains Written -> Oral Interview',
      officialNotificationUrl: 'https://psc.ap.gov.in/notifications.htm',
      officialApplicationUrl: 'https://psc.ap.gov.in',
      status: 'PUBLISHED',
      viewsCount: 1834,
      createdAt: '2026-01-10T00:00:00.000Z',
      updatedAt: '2026-01-10T00:00:00.000Z',
    },

    // Gov Job 4: RRB NTPC
    {
      id: 'job_rrb_ntpc_2026',
      title: 'Railway RRB Non-Technical Popular Categories (NTPC Graduate & Undergraduate)',
      jobType: 'GOVERNMENT',
      category: 'CENTRAL',
      organizationId: 'org_rrb',
      examinationId: 'exam_rrb_ntpc',
      qualification: 'Graduation',
      branch: 'Degree in any discipline',
      minAge: 18,
      maxAge: 36,
      salary: '₹19,900 - ₹63,200',
      vacancies: 11558,
      applicationStartDate: '2026-09-14',
      applicationEndDate: '2026-10-20',
      examDate: '2026-12-10',
      selectionProcess: 'CBT 1 -> CBT 2 -> Skill Test / Aptitude Test -> Medical',
      officialNotificationUrl: 'https://indianrailways.gov.in',
      officialApplicationUrl: 'https://indianrailways.gov.in',
      status: 'PUBLISHED',
      viewsCount: 2210,
      createdAt: '2026-09-01T00:00:00.000Z',
      updatedAt: '2026-09-01T00:00:00.000Z',
    },

    // Gov Job 5: IBPS PO
    {
      id: 'job_ibps_po_2026',
      title: 'IBPS CRP PO/MT XIV Recruitment for Probationary Officers in Public Sector Banks',
      jobType: 'GOVERNMENT',
      category: 'CENTRAL',
      organizationId: 'org_ibps',
      examinationId: 'exam_ibps_po',
      qualification: 'Graduation',
      branch: 'Any Graduate Degree',
      minAge: 20,
      maxAge: 30,
      salary: '₹52,000 - ₹65,000 CTC per month',
      vacancies: 3955,
      applicationStartDate: '2026-08-01',
      applicationEndDate: '2026-08-28',
      examDate: '2026-10-18',
      selectionProcess: 'Prelims Online Exam -> Mains Online Exam -> Interview',
      officialNotificationUrl: 'https://ibps.in',
      officialApplicationUrl: 'https://ibps.in',
      status: 'PUBLISHED',
      viewsCount: 870,
      createdAt: '2026-08-01T00:00:00.000Z',
      updatedAt: '2026-08-01T00:00:00.000Z',
    },

    // Gov Job 6: AP Police SI
    {
      id: 'job_appolice_si_2026',
      title: 'Andhra Pradesh Police SCT Sub-Inspector of Police (Civil & Armed Reserve) 2026',
      jobType: 'GOVERNMENT',
      category: 'STATE',
      stateId: 'st_ap',
      organizationId: 'org_appolice',
      examinationId: 'exam_appolice_si',
      postId: 'post_ap_si',
      qualification: 'Graduation',
      branch: 'Any Degree / B.Tech / B.Sc / B.A',
      minAge: 21,
      maxAge: 27,
      salary: '₹44,570 - ₹1,27,480 per month',
      vacancies: 411,
      applicationStartDate: '2026-03-01',
      applicationEndDate: '2026-03-25',
      examDate: '2026-06-07',
      selectionProcess: 'Preliminary Written Test -> Physical Efficiency Test -> Final Exam',
      officialNotificationUrl: 'https://slprb.ap.gov.in',
      officialApplicationUrl: 'https://slprb.ap.gov.in',
      status: 'PUBLISHED',
      viewsCount: 1610,
      createdAt: '2026-03-01T00:00:00.000Z',
      updatedAt: '2026-03-01T00:00:00.000Z',
    },

    // Gov Job 7: SSC CHSL (12th Qualification)
    {
      id: 'job_ssc_chsl_2026',
      title: 'SSC Combined Higher Secondary Level (10+2) Examination 2026 — LDC, JSA, DEO',
      jobType: 'GOVERNMENT',
      category: 'CENTRAL',
      organizationId: 'org_ssc',
      examinationId: 'exam_ssc_chsl',
      qualification: '12th',
      branch: 'Intermediate / 10+2 Pass in any stream',
      minAge: 18,
      maxAge: 27,
      salary: '₹19,900 - ₹81,100 (Level 2 to Level 5)',
      vacancies: 3712,
      applicationStartDate: '2026-04-02',
      applicationEndDate: '2026-05-01',
      examDate: '2026-07-08',
      selectionProcess: 'Tier-I (CBT) -> Tier-II (CBT & Typing/Skill Test)',
      officialNotificationUrl: 'https://ssc.gov.in',
      officialApplicationUrl: 'https://ssc.gov.in',
      status: 'PUBLISHED',
      viewsCount: 1140,
      createdAt: '2026-04-02T00:00:00.000Z',
      updatedAt: '2026-04-02T00:00:00.000Z',
    },

    // Gov Job 8: UPSC ESE (B.Tech Qualification)
    {
      id: 'job_upsc_ese_2026',
      title: 'UPSC Engineering Services Examination (IES) 2026 — Civil, Mech, Electrical, E&T',
      jobType: 'GOVERNMENT',
      category: 'CENTRAL',
      organizationId: 'org_upsc',
      examinationId: 'exam_upsc_ese',
      qualification: 'B.Tech',
      branch: 'Civil, Mechanical, Electrical, Electronics & Telecommunication',
      minAge: 21,
      maxAge: 30,
      salary: '₹56,100 - ₹1,77,500 (Level 10 Assistant Executive Engineer)',
      vacancies: 232,
      applicationStartDate: '2026-09-18',
      applicationEndDate: '2026-10-08',
      examDate: '2027-02-09',
      selectionProcess: 'Stage-I Prelims -> Stage-II Mains -> Stage-III Interview',
      officialNotificationUrl: 'https://upsc.gov.in',
      officialApplicationUrl: 'https://upsconline.nic.in',
      status: 'PUBLISHED',
      viewsCount: 750,
      createdAt: '2026-09-18T00:00:00.000Z',
      updatedAt: '2026-09-18T00:00:00.000Z',
    },

    // Private Jobs
    {
      id: 'job_priv_tcs_fullstack',
      title: 'Full Stack Software Engineer (React / Node / Cloud)',
      jobType: 'PRIVATE',
      category: 'PRIVATE',
      organizationId: 'org_tech_tcs',
      qualification: 'B.Tech',
      branch: 'Computer Science, IT, Electronics, or related',
      minAge: 20,
      maxAge: 30,
      salary: '₹6,50,000 - ₹12,00,000 per annum',
      vacancies: 'Multiple',
      applicationStartDate: '2026-08-10',
      applicationEndDate: '2026-09-30',
      selectionProcess: 'Technical Assessment (Coding & System Design) -> Managerial Interview -> HR Round',
      officialNotificationUrl: 'https://tcs.com/careers/software-engineer',
      officialApplicationUrl: 'https://tcs.com/careers',
      workMode: 'Hybrid',
      experienceRequired: '0 - 3 Years',
      skillsRequired: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Cloud / Docker'],
      location: 'Bengaluru / Hyderabad / Pune',
      sector: 'Information Technology',
      description: 'Design and develop scalable microservices, interactive web frontends, and reliable cloud-native architectures.',
      status: 'PUBLISHED',
      viewsCount: 1580,
      createdAt: '2026-08-10T00:00:00.000Z',
      updatedAt: '2026-08-10T00:00:00.000Z',
    },
    {
      id: 'job_priv_hdfc_risk',
      title: 'Credit Risk & Financial Data Analyst',
      jobType: 'PRIVATE',
      category: 'PRIVATE',
      organizationId: 'org_hdfc_bank',
      qualification: 'Graduation',
      branch: 'Commerce, Economics, Statistics, Engineering or MBA',
      minAge: 21,
      maxAge: 32,
      salary: '₹7,00,000 - ₹11,50,000 per annum',
      vacancies: 15,
      applicationStartDate: '2026-08-15',
      applicationEndDate: '2026-10-15',
      selectionProcess: 'Aptitude & Analytical Test -> Domain Interview -> HR Round',
      officialNotificationUrl: 'https://www.hdfcbank.com/careers',
      officialApplicationUrl: 'https://www.hdfcbank.com/careers',
      workMode: 'On-site',
      experienceRequired: '1 - 4 Years',
      skillsRequired: ['Financial Modeling', 'SQL', 'Data Analytics', 'Risk Assessment', 'Excel'],
      location: 'Mumbai / Hyderabad / Chennai',
      sector: 'Banking & Financial Services',
      description: 'Evaluate corporate loan exposures, assess client portfolio risk metrics, and implement automated risk mitigation algorithms.',
      status: 'PUBLISHED',
      viewsCount: 640,
      createdAt: '2026-08-15T00:00:00.000Z',
      updatedAt: '2026-08-15T00:00:00.000Z',
    },
    // Gov Job 9: SSC MTS (10th Pass)
    {
      id: 'job_ssc_mts_2026',
      title: 'SSC Multi-Tasking (Non-Technical) Staff & Havaldar (CBIC/CBN) Examination 2026',
      jobType: 'GOVERNMENT',
      category: 'CENTRAL',
      organizationId: 'org_ssc',
      qualification: '10th',
      branch: 'Matriculation (10th Class Pass) from recognized Board',
      minAge: 18,
      maxAge: 25,
      salary: '₹18,000 - ₹56,900 (Pay Level 1 Matrix)',
      vacancies: 9583,
      applicationStartDate: '2026-05-07',
      applicationEndDate: '2026-06-06',
      examDate: '2026-08-20',
      selectionProcess: 'Computer Based Examination (Session-I & II) -> Physical Standard/Efficiency (for Havaldar)',
      officialNotificationUrl: 'https://ssc.gov.in',
      officialApplicationUrl: 'https://ssc.gov.in',
      status: 'PUBLISHED',
      viewsCount: 3120,
      createdAt: '2026-05-07T00:00:00.000Z',
      updatedAt: '2026-05-07T00:00:00.000Z',
    },
    // Gov Job 10: SSC Junior Engineer (Diploma in Engineering)
    {
      id: 'job_ssc_je_2026',
      title: 'SSC Junior Engineer (Civil, Mechanical, Electrical) Recruitment 2026 — CPWD, MES, BRO',
      jobType: 'GOVERNMENT',
      category: 'CENTRAL',
      organizationId: 'org_ssc',
      qualification: 'Diploma',
      branch: 'Diploma in Civil, Mechanical, or Electrical Engineering (or Degree)',
      minAge: 18,
      maxAge: 30,
      salary: '₹35,400 - ₹1,12,400 (Level 6 Matrix)',
      vacancies: 1765,
      applicationStartDate: '2026-03-28',
      applicationEndDate: '2026-04-18',
      examDate: '2026-06-05',
      selectionProcess: 'Paper-I (Computer Based Test) -> Paper-II (Computer Based Technical Test)',
      officialNotificationUrl: 'https://ssc.gov.in',
      officialApplicationUrl: 'https://ssc.gov.in',
      status: 'PUBLISHED',
      viewsCount: 1890,
      createdAt: '2026-03-28T00:00:00.000Z',
      updatedAt: '2026-03-28T00:00:00.000Z',
    },
    ...ALL_STATE_GOVERNMENT_JOBS,
    ...ALL_STATE_PRIVATE_JOBS,
  ];

  // DYNAMIC EXAM PATTERN FOR UPSC CSE
  const examPatterns: ExamPattern[] = [
    {
      id: 'pat_upsc_cse',
      examinationId: 'exam_upsc_cse',
      title: 'UPSC Civil Services Examination Pattern (Prelims & Mains Structure)',
      description: 'Official pattern detailing preliminary objective papers, conventional written mains, and interview marking.',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'pat_ssc_cgl',
      examinationId: 'exam_ssc_cgl',
      title: 'SSC CGL Tier-I & Tier-II Computer Based Examination Scheme',
      description: 'Revised scheme with Sectional timing, module divisions, and negative marking rules.',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'pat_appsc_grp1',
      examinationId: 'exam_appsc_grp1',
      title: 'APPSC Group-I Services Screening & Written Examination Scheme',
      description: 'Comprehensive screening and 7-paper descriptive main examination structure.',
      status: 'PUBLISHED',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ];

  // UPSC Columns
  const examPatternColumns: ExamPatternColumn[] = [
    // For UPSC CSE
    { id: 'col_upsc_1', examPatternId: 'pat_upsc_cse', columnName: 'Stage', displayOrder: 1 },
    { id: 'col_upsc_2', examPatternId: 'pat_upsc_cse', columnName: 'Paper', displayOrder: 2 },
    { id: 'col_upsc_3', examPatternId: 'pat_upsc_cse', columnName: 'Subject Focus', displayOrder: 3 },
    { id: 'col_upsc_4', examPatternId: 'pat_upsc_cse', columnName: 'Type / Nature', displayOrder: 4 },
    { id: 'col_upsc_5', examPatternId: 'pat_upsc_cse', columnName: 'Questions', displayOrder: 5 },
    { id: 'col_upsc_6', examPatternId: 'pat_upsc_cse', columnName: 'Maximum Marks', displayOrder: 6 },
    { id: 'col_upsc_7', examPatternId: 'pat_upsc_cse', columnName: 'Duration', displayOrder: 7 },
    { id: 'col_upsc_8', examPatternId: 'pat_upsc_cse', columnName: 'Negative Marking', displayOrder: 8 },

    // For SSC CGL
    { id: 'col_ssc_1', examPatternId: 'pat_ssc_cgl', columnName: 'Tier', displayOrder: 1 },
    { id: 'col_ssc_2', examPatternId: 'pat_ssc_cgl', columnName: 'Section / Module', displayOrder: 2 },
    { id: 'col_ssc_3', examPatternId: 'pat_ssc_cgl', columnName: 'Subject', displayOrder: 3 },
    { id: 'col_ssc_4', examPatternId: 'pat_ssc_cgl', columnName: 'Questions', displayOrder: 4 },
    { id: 'col_ssc_5', examPatternId: 'pat_ssc_cgl', columnName: 'Marks', displayOrder: 5 },
    { id: 'col_ssc_6', examPatternId: 'pat_ssc_cgl', columnName: 'Duration', displayOrder: 6 },
    { id: 'col_ssc_7', examPatternId: 'pat_ssc_cgl', columnName: 'Negative Marking', displayOrder: 7 },

    // For APPSC Group-I
    { id: 'col_appsc_1', examPatternId: 'pat_appsc_grp1', columnName: 'Stage', displayOrder: 1 },
    { id: 'col_appsc_2', examPatternId: 'pat_appsc_grp1', columnName: 'Paper Code', displayOrder: 2 },
    { id: 'col_appsc_3', examPatternId: 'pat_appsc_grp1', columnName: 'Subject Title', displayOrder: 3 },
    { id: 'col_appsc_4', examPatternId: 'pat_appsc_grp1', columnName: 'Nature', displayOrder: 4 },
    { id: 'col_appsc_5', examPatternId: 'pat_appsc_grp1', columnName: 'Total Marks', displayOrder: 5 },
    { id: 'col_appsc_6', examPatternId: 'pat_appsc_grp1', columnName: 'Duration', displayOrder: 6 },
  ];

  // UPSC Rows & Cells
  const examPatternRows: ExamPatternRow[] = [
    // UPSC Rows
    { id: 'row_upsc_1', examPatternId: 'pat_upsc_cse', displayOrder: 1 },
    { id: 'row_upsc_2', examPatternId: 'pat_upsc_cse', displayOrder: 2 },
    { id: 'row_upsc_3', examPatternId: 'pat_upsc_cse', displayOrder: 3 },
    { id: 'row_upsc_4', examPatternId: 'pat_upsc_cse', displayOrder: 4 },
    { id: 'row_upsc_5', examPatternId: 'pat_upsc_cse', displayOrder: 5 },
    { id: 'row_upsc_6', examPatternId: 'pat_upsc_cse', displayOrder: 6 },
    { id: 'row_upsc_7', examPatternId: 'pat_upsc_cse', displayOrder: 7 },

    // SSC Rows
    { id: 'row_ssc_1', examPatternId: 'pat_ssc_cgl', displayOrder: 1 },
    { id: 'row_ssc_2', examPatternId: 'pat_ssc_cgl', displayOrder: 2 },
    { id: 'row_ssc_3', examPatternId: 'pat_ssc_cgl', displayOrder: 3 },
    { id: 'row_ssc_4', examPatternId: 'pat_ssc_cgl', displayOrder: 4 },
    { id: 'row_ssc_5', examPatternId: 'pat_ssc_cgl', displayOrder: 5 },

    // APPSC Rows
    { id: 'row_ap_1', examPatternId: 'pat_appsc_grp1', displayOrder: 1 },
    { id: 'row_ap_2', examPatternId: 'pat_appsc_grp1', displayOrder: 2 },
    { id: 'row_ap_3', examPatternId: 'pat_appsc_grp1', displayOrder: 3 },
    { id: 'row_ap_4', examPatternId: 'pat_appsc_grp1', displayOrder: 4 },
  ];

  const examPatternCells: ExamPatternCell[] = [
    // UPSC Row 1: Prelims GS I
    { id: 'c_u1_1', rowId: 'row_upsc_1', columnId: 'col_upsc_1', cellValue: 'Prelims' },
    { id: 'c_u1_2', rowId: 'row_upsc_1', columnId: 'col_upsc_2', cellValue: 'Paper I' },
    { id: 'c_u1_3', rowId: 'row_upsc_1', columnId: 'col_upsc_3', cellValue: 'General Studies I (History, Polity, Geo, Eco, Env)' },
    { id: 'c_u1_4', rowId: 'row_upsc_1', columnId: 'col_upsc_4', cellValue: 'Objective (MCQ)' },
    { id: 'c_u1_5', rowId: 'row_upsc_1', columnId: 'col_upsc_5', cellValue: '100 Questions' },
    { id: 'c_u1_6', rowId: 'row_upsc_1', columnId: 'col_upsc_6', cellValue: '200 Marks' },
    { id: 'c_u1_7', rowId: 'row_upsc_1', columnId: 'col_upsc_7', cellValue: '2 Hours' },
    { id: 'c_u1_8', rowId: 'row_upsc_1', columnId: 'col_upsc_8', cellValue: '1/3rd (0.66 marks deducted)' },

    // UPSC Row 2: Prelims GS II (CSAT)
    { id: 'c_u2_1', rowId: 'row_upsc_2', columnId: 'col_upsc_1', cellValue: 'Prelims' },
    { id: 'c_u2_2', rowId: 'row_upsc_2', columnId: 'col_upsc_2', cellValue: 'Paper II' },
    { id: 'c_u2_3', rowId: 'row_upsc_2', columnId: 'col_upsc_3', cellValue: 'CSAT (Reasoning, Comprehension & Aptitude)' },
    { id: 'c_u2_4', rowId: 'row_upsc_2', columnId: 'col_upsc_4', cellValue: 'Objective (Qualifying 33%)' },
    { id: 'c_u2_5', rowId: 'row_upsc_2', columnId: 'col_upsc_5', cellValue: '80 Questions' },
    { id: 'c_u2_6', rowId: 'row_upsc_2', columnId: 'col_upsc_6', cellValue: '200 Marks' },
    { id: 'c_u2_7', rowId: 'row_upsc_2', columnId: 'col_upsc_7', cellValue: '2 Hours' },
    { id: 'c_u2_8', rowId: 'row_upsc_2', columnId: 'col_upsc_8', cellValue: '1/3rd (0.83 marks deducted)' },

    // UPSC Row 3: Mains Essay
    { id: 'c_u3_1', rowId: 'row_upsc_3', columnId: 'col_upsc_1', cellValue: 'Mains' },
    { id: 'c_u3_2', rowId: 'row_upsc_3', columnId: 'col_upsc_2', cellValue: 'Paper I' },
    { id: 'c_u3_3', rowId: 'row_upsc_3', columnId: 'col_upsc_3', cellValue: 'Essay (Two sections / Philosophical & Contemporary)' },
    { id: 'c_u3_4', rowId: 'row_upsc_3', columnId: 'col_upsc_4', cellValue: 'Conventional Descriptive' },
    { id: 'c_u3_5', rowId: 'row_upsc_3', columnId: 'col_upsc_5', cellValue: '2 Essays' },
    { id: 'c_u3_6', rowId: 'row_upsc_3', columnId: 'col_upsc_6', cellValue: '250 Marks' },
    { id: 'c_u3_7', rowId: 'row_upsc_3', columnId: 'col_upsc_7', cellValue: '3 Hours' },
    { id: 'c_u3_8', rowId: 'row_upsc_3', columnId: 'col_upsc_8', cellValue: 'None' },

    // UPSC Row 4: Mains GS I to IV
    { id: 'c_u4_1', rowId: 'row_upsc_4', columnId: 'col_upsc_1', cellValue: 'Mains' },
    { id: 'c_u4_2', rowId: 'row_upsc_4', columnId: 'col_upsc_2', cellValue: 'Paper II to V' },
    { id: 'c_u4_3', rowId: 'row_upsc_4', columnId: 'col_upsc_3', cellValue: 'General Studies I, II, III & IV (Ethics)' },
    { id: 'c_u4_4', rowId: 'row_upsc_4', columnId: 'col_upsc_4', cellValue: 'Conventional Descriptive' },
    { id: 'c_u4_5', rowId: 'row_upsc_4', columnId: 'col_upsc_5', cellValue: '20 Questions each' },
    { id: 'c_u4_6', rowId: 'row_upsc_4', columnId: 'col_upsc_6', cellValue: '1000 Marks (250 x 4)' },
    { id: 'c_u4_7', rowId: 'row_upsc_4', columnId: 'col_upsc_7', cellValue: '3 Hours each' },
    { id: 'c_u4_8', rowId: 'row_upsc_4', columnId: 'col_upsc_8', cellValue: 'None' },

    // UPSC Row 5: Mains Optional
    { id: 'c_u5_1', rowId: 'row_upsc_5', columnId: 'col_upsc_1', cellValue: 'Mains' },
    { id: 'c_u5_2', rowId: 'row_upsc_5', columnId: 'col_upsc_2', cellValue: 'Paper VI & VII' },
    { id: 'c_u5_3', rowId: 'row_upsc_5', columnId: 'col_upsc_3', cellValue: 'Optional Subject (Paper 1 & Paper 2)' },
    { id: 'c_u5_4', rowId: 'row_upsc_5', columnId: 'col_upsc_4', cellValue: 'Conventional Descriptive' },
    { id: 'c_u5_5', rowId: 'row_upsc_5', columnId: 'col_upsc_5', cellValue: '5 Questions per paper' },
    { id: 'c_u5_6', rowId: 'row_upsc_5', columnId: 'col_upsc_6', cellValue: '500 Marks (250 x 2)' },
    { id: 'c_u5_7', rowId: 'row_upsc_5', columnId: 'col_upsc_7', cellValue: '3 Hours each' },
    { id: 'c_u5_8', rowId: 'row_upsc_5', columnId: 'col_upsc_8', cellValue: 'None' },

    // UPSC Row 6: Personality Test
    { id: 'c_u6_1', rowId: 'row_upsc_6', columnId: 'col_upsc_1', cellValue: 'Interview' },
    { id: 'c_u6_2', rowId: 'row_upsc_6', columnId: 'col_upsc_2', cellValue: 'Final Stage' },
    { id: 'c_u6_3', rowId: 'row_upsc_6', columnId: 'col_upsc_3', cellValue: 'Personality Test & Viva Voce' },
    { id: 'c_u6_4', rowId: 'row_upsc_6', columnId: 'col_upsc_4', cellValue: 'Oral Assessment by Board' },
    { id: 'c_u6_5', rowId: 'row_upsc_6', columnId: 'col_upsc_5', cellValue: 'Comprehensive Board' },
    { id: 'c_u6_6', rowId: 'row_upsc_6', columnId: 'col_upsc_6', cellValue: '275 Marks' },
    { id: 'c_u6_7', rowId: 'row_upsc_6', columnId: 'col_upsc_7', cellValue: '30 - 45 Mins' },
    { id: 'c_u6_8', rowId: 'row_upsc_6', columnId: 'col_upsc_8', cellValue: 'None' },

    // UPSC Row 7: Grand Total
    { id: 'c_u7_1', rowId: 'row_upsc_7', columnId: 'col_upsc_1', cellValue: 'Total' },
    { id: 'c_u7_2', rowId: 'row_upsc_7', columnId: 'col_upsc_2', cellValue: 'Merit List' },
    { id: 'c_u7_3', rowId: 'row_upsc_7', columnId: 'col_upsc_3', cellValue: 'Written Mains (1750) + Interview (275)' },
    { id: 'c_u7_4', rowId: 'row_upsc_7', columnId: 'col_upsc_4', cellValue: 'Rank Determination' },
    { id: 'c_u7_5', rowId: 'row_upsc_7', columnId: 'col_upsc_5', cellValue: 'All Scored Papers' },
    { id: 'c_u7_6', rowId: 'row_upsc_7', columnId: 'col_upsc_6', cellValue: '2025 Marks' },
    { id: 'c_u7_7', rowId: 'row_upsc_7', columnId: 'col_upsc_7', cellValue: 'Complete Process' },
    { id: 'c_u7_8', rowId: 'row_upsc_7', columnId: 'col_upsc_8', cellValue: 'Final Cut-off' },

    // SSC Row 1: Tier 1
    { id: 'c_s1_1', rowId: 'row_ssc_1', columnId: 'col_ssc_1', cellValue: 'Tier-I' },
    { id: 'c_s1_2', rowId: 'row_ssc_1', columnId: 'col_ssc_2', cellValue: 'Module 1' },
    { id: 'c_s1_3', rowId: 'row_ssc_1', columnId: 'col_ssc_3', cellValue: 'General Intelligence & Reasoning' },
    { id: 'c_s1_4', rowId: 'row_ssc_1', columnId: 'col_ssc_4', cellValue: '25' },
    { id: 'c_s1_5', rowId: 'row_ssc_1', columnId: 'col_ssc_5', cellValue: '50' },
    { id: 'c_s1_6', rowId: 'row_ssc_1', columnId: 'col_ssc_6', cellValue: '60 Minutes (Composite)' },
    { id: 'c_s1_7', rowId: 'row_ssc_1', columnId: 'col_ssc_7', cellValue: '0.50 marks' },

    // SSC Row 2: Tier 1 GS
    { id: 'c_s2_1', rowId: 'row_ssc_2', columnId: 'col_ssc_1', cellValue: 'Tier-I' },
    { id: 'c_s2_2', rowId: 'row_ssc_2', columnId: 'col_ssc_2', cellValue: 'Module 2' },
    { id: 'c_s2_3', rowId: 'row_ssc_2', columnId: 'col_ssc_3', cellValue: 'General Awareness' },
    { id: 'c_s2_4', rowId: 'row_ssc_2', columnId: 'col_ssc_4', cellValue: '25' },
    { id: 'c_s2_5', rowId: 'row_ssc_2', columnId: 'col_ssc_5', cellValue: '50' },
    { id: 'c_s2_6', rowId: 'row_ssc_2', columnId: 'col_ssc_6', cellValue: '60 Minutes (Composite)' },
    { id: 'c_s2_7', rowId: 'row_ssc_2', columnId: 'col_ssc_7', cellValue: '0.50 marks' },

    // SSC Row 3: Tier 1 Quant
    { id: 'c_s3_1', rowId: 'row_ssc_3', columnId: 'col_ssc_1', cellValue: 'Tier-I' },
    { id: 'c_s3_2', rowId: 'row_ssc_3', columnId: 'col_ssc_2', cellValue: 'Module 3' },
    { id: 'c_s3_3', rowId: 'row_ssc_3', columnId: 'col_ssc_3', cellValue: 'Quantitative Aptitude' },
    { id: 'c_s3_4', rowId: 'row_ssc_3', columnId: 'col_ssc_4', cellValue: '25' },
    { id: 'c_s3_5', rowId: 'row_ssc_3', columnId: 'col_ssc_5', cellValue: '50' },
    { id: 'c_s3_6', rowId: 'row_ssc_3', columnId: 'col_ssc_6', cellValue: '60 Minutes (Composite)' },
    { id: 'c_s3_7', rowId: 'row_ssc_3', columnId: 'col_ssc_7', cellValue: '0.50 marks' },

    // SSC Row 4: Tier 1 English
    { id: 'c_s4_1', rowId: 'row_ssc_4', columnId: 'col_ssc_1', cellValue: 'Tier-I' },
    { id: 'c_s4_2', rowId: 'row_ssc_4', columnId: 'col_ssc_2', cellValue: 'Module 4' },
    { id: 'c_s4_3', rowId: 'row_ssc_4', columnId: 'col_ssc_3', cellValue: 'English Comprehension' },
    { id: 'c_s4_4', rowId: 'row_ssc_4', columnId: 'col_ssc_4', cellValue: '25' },
    { id: 'c_s4_5', rowId: 'row_ssc_4', columnId: 'col_ssc_5', cellValue: '50' },
    { id: 'c_s4_6', rowId: 'row_ssc_4', columnId: 'col_ssc_6', cellValue: '60 Minutes (Composite)' },
    { id: 'c_s4_7', rowId: 'row_ssc_4', columnId: 'col_ssc_7', cellValue: '0.50 marks' },

    // SSC Row 5: Tier 2 Section 1
    { id: 'c_s5_1', rowId: 'row_ssc_5', columnId: 'col_ssc_1', cellValue: 'Tier-II' },
    { id: 'c_s5_2', rowId: 'row_ssc_5', columnId: 'col_ssc_2', cellValue: 'Section I & II' },
    { id: 'c_s5_3', rowId: 'row_ssc_5', columnId: 'col_ssc_3', cellValue: 'Maths, Reasoning, English & GA' },
    { id: 'c_s5_4', rowId: 'row_ssc_5', columnId: 'col_ssc_4', cellValue: '130' },
    { id: 'c_s5_5', rowId: 'row_ssc_5', columnId: 'col_ssc_5', cellValue: '390' },
    { id: 'c_s5_6', rowId: 'row_ssc_5', columnId: 'col_ssc_6', cellValue: '2 Hours 15 Mins' },
    { id: 'c_s5_7', rowId: 'row_ssc_5', columnId: 'col_ssc_7', cellValue: '1 mark per wrong' },

    // APPSC Group 1 Row 1
    { id: 'c_ap1_1', rowId: 'row_ap_1', columnId: 'col_appsc_1', cellValue: 'Screening Test' },
    { id: 'c_ap1_2', rowId: 'row_ap_1', columnId: 'col_appsc_2', cellValue: 'Paper I' },
    { id: 'c_ap1_3', rowId: 'row_ap_1', columnId: 'col_appsc_3', cellValue: 'General Studies & Mental Ability' },
    { id: 'c_ap1_4', rowId: 'row_ap_1', columnId: 'col_appsc_4', cellValue: 'Objective Type (OMR/CBT)' },
    { id: 'c_ap1_5', rowId: 'row_ap_1', columnId: 'col_appsc_5', cellValue: '120 Marks' },
    { id: 'c_ap1_6', rowId: 'row_ap_1', columnId: 'col_appsc_6', cellValue: '120 Minutes' },

    // APPSC Group 1 Row 2
    { id: 'c_ap2_1', rowId: 'row_ap_2', columnId: 'col_appsc_1', cellValue: 'Screening Test' },
    { id: 'c_ap2_2', rowId: 'row_ap_2', columnId: 'col_appsc_2', cellValue: 'Paper II' },
    { id: 'c_ap2_3', rowId: 'row_ap_2', columnId: 'col_appsc_3', cellValue: 'General Aptitude (Science & Tech, Indian Economy)' },
    { id: 'c_ap2_4', rowId: 'row_ap_2', columnId: 'col_appsc_4', cellValue: 'Objective Type (OMR/CBT)' },
    { id: 'c_ap2_5', rowId: 'row_ap_2', columnId: 'col_appsc_5', cellValue: '120 Marks' },
    { id: 'c_ap2_6', rowId: 'row_ap_2', columnId: 'col_appsc_6', cellValue: '120 Minutes' },

    // APPSC Group 1 Row 3
    { id: 'c_ap3_1', rowId: 'row_ap_3', columnId: 'col_appsc_1', cellValue: 'Mains Written' },
    { id: 'c_ap3_2', rowId: 'row_ap_3', columnId: 'col_appsc_2', cellValue: 'Paper I to V' },
    { id: 'c_ap3_3', rowId: 'row_ap_3', columnId: 'col_appsc_3', cellValue: 'Essay, History/Culture, Polity/Gov, Economy, Science/Tech' },
    { id: 'c_ap3_4', rowId: 'row_ap_3', columnId: 'col_appsc_4', cellValue: 'Conventional Descriptive' },
    { id: 'c_ap3_5', rowId: 'row_ap_3', columnId: 'col_appsc_5', cellValue: '750 Marks (150 x 5)' },
    { id: 'c_ap3_6', rowId: 'row_ap_3', columnId: 'col_appsc_6', cellValue: '180 Minutes each' },

    // APPSC Group 1 Row 4
    { id: 'c_ap4_1', rowId: 'row_ap_4', columnId: 'col_appsc_1', cellValue: 'Final Stage' },
    { id: 'c_ap4_2', rowId: 'row_ap_4', columnId: 'col_appsc_2', cellValue: 'Oral Test' },
    { id: 'c_ap4_3', rowId: 'row_ap_4', columnId: 'col_appsc_3', cellValue: 'Personal Interview & Viva Voce' },
    { id: 'c_ap4_4', rowId: 'row_ap_4', columnId: 'col_appsc_4', cellValue: 'Direct Assessment' },
    { id: 'c_ap4_5', rowId: 'row_ap_4', columnId: 'col_appsc_5', cellValue: '75 Marks' },
    { id: 'c_ap4_6', rowId: 'row_ap_4', columnId: 'col_appsc_6', cellValue: '25 - 35 Minutes' },
  ];

  // DYNAMIC SYLLABUS
  const syllabusSubjects: SyllabusSubject[] = [
    // UPSC CSE Subjects
    { id: 'sub_upsc_gs', examinationId: 'exam_upsc_cse', name: 'General Studies (Prelims Paper I)', displayOrder: 1 },
    { id: 'sub_upsc_csat', examinationId: 'exam_upsc_cse', name: 'CSAT / Civil Services Aptitude Test (Prelims Paper II)', displayOrder: 2 },
    { id: 'sub_upsc_mains_gs1', examinationId: 'exam_upsc_cse', name: 'Mains GS Paper I: Indian Heritage, History & Geography', displayOrder: 3 },
    { id: 'sub_upsc_mains_gs2', examinationId: 'exam_upsc_cse', name: 'Mains GS Paper II: Governance, Constitution & Polity', displayOrder: 4 },
    { id: 'sub_upsc_mains_gs3', examinationId: 'exam_upsc_cse', name: 'Mains GS Paper III: Technology, Economic Development & Security', displayOrder: 5 },
    { id: 'sub_upsc_mains_gs4', examinationId: 'exam_upsc_cse', name: 'Mains GS Paper IV: Ethics, Integrity & Aptitude', displayOrder: 6 },

    // SSC CGL Subjects
    { id: 'sub_ssc_quant', examinationId: 'exam_ssc_cgl', name: 'Quantitative Aptitude', displayOrder: 1 },
    { id: 'sub_ssc_reasoning', examinationId: 'exam_ssc_cgl', name: 'General Intelligence & Reasoning', displayOrder: 2 },
    { id: 'sub_ssc_english', examinationId: 'exam_ssc_cgl', name: 'English Language & Comprehension', displayOrder: 3 },
    { id: 'sub_ssc_ga', examinationId: 'exam_ssc_cgl', name: 'General Awareness & Current Affairs', displayOrder: 4 },

    // APPSC Group-I Subjects
    { id: 'sub_ap_hist', examinationId: 'exam_appsc_grp1', name: 'History, Culture & Geography of India and Andhra Pradesh', displayOrder: 1 },
    { id: 'sub_ap_polity', examinationId: 'exam_appsc_grp1', name: 'Polity, Constitution, Governance, Law & Ethics', displayOrder: 2 },
    { id: 'sub_ap_eco', examinationId: 'exam_appsc_grp1', name: 'Economy & Development of India and Andhra Pradesh', displayOrder: 3 },
  ];

  const syllabusTopics: SyllabusTopic[] = [
    // UPSC GS Topics
    { id: 'top_u_hist', subjectId: 'sub_upsc_gs', name: 'History of India and Indian National Movement', displayOrder: 1 },
    { id: 'top_u_geo', subjectId: 'sub_upsc_gs', name: 'Indian and World Geography', displayOrder: 2 },
    { id: 'top_u_polity', subjectId: 'sub_upsc_gs', name: 'Indian Polity and Governance', displayOrder: 3 },
    { id: 'top_u_eco', subjectId: 'sub_upsc_gs', name: 'Economic and Social Development', displayOrder: 4 },
    { id: 'top_u_env', subjectId: 'sub_upsc_gs', name: 'General Issues on Environmental Ecology, Bio-diversity & Climate Change', displayOrder: 5 },

    // UPSC CSAT Topics
    { id: 'top_u_csat_comp', subjectId: 'sub_upsc_csat', name: 'Reading Comprehension', displayOrder: 1 },
    { id: 'top_u_csat_logic', subjectId: 'sub_upsc_csat', name: 'Logical Reasoning & Analytical Ability', displayOrder: 2 },
    { id: 'top_u_csat_num', subjectId: 'sub_upsc_csat', name: 'Basic Numeracy (Class X level) & Data Interpretation', displayOrder: 3 },

    // SSC Quant Topics
    { id: 'top_s_arithmetic', subjectId: 'sub_ssc_quant', name: 'Arithmetic & Commercial Mathematics', displayOrder: 1 },
    { id: 'top_s_advanced', subjectId: 'sub_ssc_quant', name: 'Algebra, Geometry, Trigonometry & Mensuration', displayOrder: 2 },
    { id: 'top_s_numbers', subjectId: 'sub_ssc_quant', name: 'Number Systems & Computation of Whole Numbers', displayOrder: 3 },

    // SSC Reasoning Topics
    { id: 'top_s_verbal', subjectId: 'sub_ssc_reasoning', name: 'Verbal Reasoning & Analogies', displayOrder: 1 },
    { id: 'top_s_nonverbal', subjectId: 'sub_ssc_reasoning', name: 'Non-Verbal & Spatial Orientation', displayOrder: 2 },

    // APPSC History Topics
    { id: 'top_ap_ancient', subjectId: 'sub_ap_hist', name: 'History and Culture of Ancient & Medieval Andhra (Satavahanas to Kakatiyas)', displayOrder: 1 },
    { id: 'top_ap_modern', subjectId: 'sub_ap_hist', name: 'Freedom Struggle & Andhra Movement for Statehood (1900-1956)', displayOrder: 2 },
    { id: 'top_ap_reorg', subjectId: 'sub_ap_hist', name: 'Bifurcation of Andhra Pradesh & Andhra Pradesh Reorganization Act 2014', displayOrder: 3 },
  ];

  const syllabusSubtopics: SyllabusSubtopic[] = [
    // Under UPSC History
    { id: 'subtop_1', topicId: 'top_u_hist', name: 'Ancient India: Harappan Civilization, Vedic Age, Buddhism and Jainism', displayOrder: 1 },
    { id: 'subtop_2', topicId: 'top_u_hist', name: 'Medieval India: Delhi Sultanate, Mughal Administration, Bhakti and Sufi Movements', displayOrder: 2 },
    { id: 'subtop_3', topicId: 'top_u_hist', name: 'Modern India: British Expansion, 1857 Revolt, Socio-Religious Reforms', displayOrder: 3 },
    { id: 'subtop_4', topicId: 'top_u_hist', name: 'Gandhian Era & Mass Movements (Non-Cooperation, Civil Disobedience, Quit India)', displayOrder: 4 },

    // Under UPSC Polity
    { id: 'subtop_5', topicId: 'top_u_polity', name: 'Constitution: Preamble, Fundamental Rights, Fundamental Duties & DPSP', displayOrder: 1 },
    { id: 'subtop_6', topicId: 'top_u_polity', name: 'Union and State Executives: President, Prime Minister, Governor, Council of Ministers', displayOrder: 2 },
    { id: 'subtop_7', topicId: 'top_u_polity', name: 'Judiciary: Supreme Court, High Courts, Judicial Review & Public Interest Litigation', displayOrder: 3 },
    { id: 'subtop_8', topicId: 'top_u_polity', name: 'Panchayati Raj, Municipalities, and Decentralized Democratic Planning', displayOrder: 4 },

    // Under SSC Arithmetic
    { id: 'subtop_9', topicId: 'top_s_arithmetic', name: 'Percentages, Ratio and Proportion, Average, Interest (Simple & Compound)', displayOrder: 1 },
    { id: 'subtop_10', topicId: 'top_s_arithmetic', name: 'Profit & Loss, Discount, Partnership Business, Mixture and Alligation', displayOrder: 2 },
    { id: 'subtop_11', topicId: 'top_s_arithmetic', name: 'Time and Distance, Time and Work, Pipes and Cisterns', displayOrder: 3 },

    // Under SSC Advanced
    { id: 'subtop_12', topicId: 'top_s_advanced', name: 'Algebra: Basic algebraic identities, Graphs of Linear Equations', displayOrder: 1 },
    { id: 'subtop_13', topicId: 'top_s_advanced', name: 'Geometry: Triangles, Circles, Tangents, Common chords, Polygons', displayOrder: 2 },
    { id: 'subtop_14', topicId: 'top_s_advanced', name: 'Trigonometry: Heights and Distances, Standard Identities (sin, cos, tan)', displayOrder: 3 },

    // Under AP Reorg
    { id: 'subtop_15', topicId: 'top_ap_reorg', name: 'Analysis of AP Reorganization Act 2014 provisions and institutional division', displayOrder: 1 },
    { id: 'subtop_16', topicId: 'top_ap_reorg', name: 'Division of Assets, Liabilities, and River Water Sharing (Krishna & Godavari)', displayOrder: 2 },
    { id: 'subtop_17', topicId: 'top_ap_reorg', name: 'Capital City construction and developmental trajectories of residual Andhra Pradesh', displayOrder: 3 },
  ];

  // PREPARATION ROADMAP
  const preparationRoadmaps: PreparationRoadmapPhase[] = [
    // UPSC Roadmap
    {
      id: 'rd_upsc_1',
      examinationId: 'exam_upsc_cse',
      phaseNumber: 1,
      title: 'Phase 1 — NCERT Foundation & Syllabus Mapping',
      duration: 'Months 1 to 3',
      description: 'Master foundational concepts from Class VI to XII NCERT textbooks across History, Geography, Polity, and Economics. Read the official syllabus line-by-line and align daily news reading.',
      keyActionPoints: [
        'Read NCERTs (Class 6-12) for History, Geography, Polity, Economics, and Science',
        'Establish a consistent habit of reading The Hindu / Indian Express daily editorial analysis',
        'Memorize the Prelims and Mains official syllabus topics to filter out irrelevant information',
        'Analyze the last 10 years of UPSC Prelims and Mains question trends'
      ],
    },
    {
      id: 'rd_upsc_2',
      examinationId: 'exam_upsc_cse',
      phaseNumber: 2,
      title: 'Phase 2 — Standard Textbooks & Consolidated Notes',
      duration: 'Months 4 to 7',
      description: 'Progress into core reference texts: Laxmikanth (Polity), Spectrum / Bipan Chandra (Modern History), Shankar IAS / PMF IAS (Environment), and Ramesh Singh (Economy).',
      keyActionPoints: [
        'Read M. Laxmikanth for Indian Polity thoroughly; solve chapter-wise MCQs',
        'Study GC Leong & Oxford Student Atlas for Physical and Human Geography',
        'Finalize your Optional Subject and complete at least 60% of Paper 1 syllabus',
        'Synthesize monthly current affairs compilations into concise revision flashcards'
      ],
    },
    {
      id: 'rd_upsc_3',
      examinationId: 'exam_upsc_cse',
      phaseNumber: 3,
      title: 'Phase 3 — Previous Question Mastery & Answer Writing',
      duration: 'Months 8 to 10',
      description: 'Transition into rigorous answer writing practice. Learn structured introduction-body-conclusion formats, diagram integration, and case law citations.',
      keyActionPoints: [
        'Write 2 to 3 Mains questions every day with timer adherence (7 to 9 minutes per question)',
        'Complete thematic study of Ethics (GS IV) with 30+ real-world case studies',
        'Solve 5000+ topic-wise previous year questions (PYQs) for Prelims',
        'Engage in weekly simulated peer reviews or mentor answer evaluations'
      ],
    },
    {
      id: 'rd_upsc_4',
      examinationId: 'exam_upsc_cse',
      phaseNumber: 4,
      title: 'Phase 4 — Intensive Prelims Mocks & CSAT Drills',
      duration: 'Months 11 to 12',
      description: 'Shift 100% focus to Prelims 60 days before the exam date. Practice exam simulation in the exact 9:30 AM and 2:30 PM time slots.',
      keyActionPoints: [
        'Attempt 35 to 45 full-length GS Paper I mock tests in exam conditions',
        'Dedicate 1.5 hours daily to CSAT (Paper II) to guarantee scoring safely above 40% (80+ marks)',
        'Maintain an Error Log Book to prevent recurring silly mistakes',
        'Revise Year-Round Government Schemes, Budget, and Economic Survey summaries'
      ],
    },
    {
      id: 'rd_upsc_5',
      examinationId: 'exam_upsc_cse',
      phaseNumber: 5,
      title: 'Phase 5 — Mains Specialization & Test Series',
      duration: 'Months 13 to 15 (Post-Prelims)',
      description: 'Intense 90-day marathon between Prelims result and Mains examination. Focus exclusively on speed, stamina, Optional mastery, and Essay writing.',
      keyActionPoints: [
        'Write 8 full-length Mains simulation tests (GS I to IV + Essay + Optional)',
        'Prepare 1-page summaries for 100 high-probability current governance issues',
        'Refine answer enrichment: quote NITI Aayog reports, 2nd ARC recommendations, and Law Commission reports',
        'Practice writing continuously for 6 hours a day (two 3-hour papers) to build hand stamina'
      ],
    },
    {
      id: 'rd_upsc_6',
      examinationId: 'exam_upsc_cse',
      phaseNumber: 6,
      title: 'Phase 6 — Personality Test & DAF Preparation',
      duration: 'Final Phase',
      description: 'Prepare every keyword in your Detailed Application Form (DAF) including home state, hobbies, graduation subjects, and service preferences.',
      keyActionPoints: [
        'Deep-dive into district, state, and national socio-economic current debates',
        'Participate in 3 to 4 reputable mock interview panels for body language and voice modulation',
        'Cultivate balanced, constitutional, and solution-oriented opinions without bias',
        'Practice articulating thoughts clearly, politely, and honestly under pressure'
      ],
    },

    // SSC CGL Roadmap
    {
      id: 'rd_ssc_1',
      examinationId: 'exam_ssc_cgl',
      phaseNumber: 1,
      title: 'Phase 1 — Concept Clearance & Mathematical Formulae',
      duration: 'Months 1 to 2',
      description: 'Understand core arithmetic, algebra, trigonometry identities, and English grammar rules.',
      keyActionPoints: [
        'Learn tables up to 30, squares up to 50, cubes up to 30, and fraction-to-percentage conversions',
        'Study Neetu Singh Volume 1 or Wren & Martin for fundamental English grammar rules',
        'Solve 50 basic reasoning puzzles and pattern series daily'
      ],
    },
    {
      id: 'rd_ssc_2',
      examinationId: 'exam_ssc_cgl',
      phaseNumber: 2,
      title: 'Phase 2 — Sectional Speed Drills & Chapter Tests',
      duration: 'Months 3 to 4',
      description: 'Master time allocation per section: Reasoning (12-15m), GK (5-7m), English (10-12m), Quant (25m).',
      keyActionPoints: [
        'Practice 100 Kiran/Pinnacle chapter-wise questions every single day',
        'Build speed using mental math and elimination techniques',
        'Study Lucent GK and monthly current affairs capsule'
      ],
    },
    {
      id: 'rd_ssc_3',
      examinationId: 'exam_ssc_cgl',
      phaseNumber: 3,
      title: 'Phase 3 — Full Length Computer Mocks & Tier-II Alignment',
      duration: 'Months 5 to 6',
      description: 'Take 50+ computer-based mock tests, analyze percentile scores, and practice computer module & typing daily.',
      keyActionPoints: [
        'Attempt 1 full mock test every morning; spend 2 hours analyzing mistakes',
        'Target 150+ raw marks in Tier-I mocks',
        'Practice 15 minutes of English touch-typing daily to cross 35 words per minute (WPM)'
      ],
    },
  ];

  // NOTICES & ANNOUNCEMENTS
  const notices: Notice[] = [
    {
      id: 'not_1',
      title: 'UPSC Civil Services 2026 Official Notification Published — 1056 Vacancies',
      organizationName: 'UPSC',
      category: 'CENTRAL',
      status: 'NEW',
      date: '2026-02-14',
      linkUrl: 'https://upsc.gov.in',
      isImportant: true,
    },
    {
      id: 'not_2',
      title: 'APPSC Group-I Preliminary Screening Test Exam Center Allotment & Hall Tickets',
      organizationName: 'APPSC',
      category: 'STATE',
      status: 'IMPORTANT',
      date: '2026-03-01',
      linkUrl: 'https://psc.ap.gov.in',
      isImportant: true,
    },
    {
      id: 'not_3',
      title: 'SSC CGL Tier-I Revised Normalization Formula & Shift Schedule Released',
      organizationName: 'SSC',
      category: 'CENTRAL',
      status: 'UPDATED',
      date: '2026-02-28',
      linkUrl: 'https://ssc.gov.in',
      isImportant: false,
    },
    {
      id: 'not_4',
      title: 'Railway RRB NTPC Document Verification & Medical Examination Standards Guide',
      organizationName: 'Indian Railways',
      category: 'EXAM_UPDATE',
      status: 'NEW',
      date: '2026-02-20',
      linkUrl: 'https://indianrailways.gov.in',
      isImportant: false,
    },
  ];

  const announcements: Announcement[] = [
    {
      id: 'anc_1',
      title: 'Welcome to CAREER DEFINER — Independent National Employment Portal',
      content: 'Define your career and discover verified recruitment updates, eligibility criteria, syllabi, and preparation roadmaps across Central and State services.',
      category: 'Platform Updates',
      date: '2026-02-15',
      isActive: true,
    },
    {
      id: 'anc_2',
      title: 'Special Advisory: Always Verify Details from Official Government Websites',
      content: 'Career Definer provides reference and guidance information. Candidates are strongly advised to verify recruitment dates, age limits, and instructions through official notifications.',
      category: 'Important Announcements',
      date: '2026-02-01',
      isActive: true,
    },
    {
      id: 'anc_3',
      title: 'Upcoming Mega State Public Service Commission Calendar (APPSC, TSPSC, KPSC)',
      content: 'State recruitment commissions have scheduled upcoming Group-I, Group-II, and Police Sub-Inspector notifications for Q2 2026.',
      category: 'Exam Updates',
      date: '2026-02-10',
      isActive: true,
    },
  ];

  const notifications: Notification[] = [
    {
      id: 'ntf_1',
      title: 'Application Deadline Approaching: UPSC Civil Services 2026',
      message: 'The online application portal for UPSC Civil Services Examination 2026 closes on 5th March 2026 at 6:00 PM. Apply now through the official website.',
      targetAudience: 'Graduates',
      linkUrl: '/jobs/job_upsc_cse_2026',
      createdAt: '2026-02-25T10:00:00.000Z',
    },
    {
      id: 'ntf_2',
      title: 'New State Opportunity: APPSC Group-I Executive Cadre',
      message: '89 Group-I Executive & Administrative posts announced. Check your eligibility criteria on Career Definer.',
      targetAudience: 'State',
      targetValue: 'Andhra Pradesh',
      linkUrl: '/jobs/job_appsc_grp1_2026',
      createdAt: '2026-02-20T08:00:00.000Z',
    },
  ];

  return {
    users,
    studentProfiles,
    states,
    sectors,
    organizations,
    departments,
    examinations,
    examGroups,
    postsServices,
    jobs,
    savedJobs: [],
    examPatterns,
    examPatternColumns,
    examPatternRows,
    examPatternCells,
    syllabusSubjects,
    syllabusTopics,
    syllabusSubtopics,
    preparationRoadmaps,
    notices,
    announcements,
    notifications,
    userNotificationReads: [],
    careerRoadmaps: INITIAL_CAREER_ROADMAPS,
    studentRoadmapProgress: [],
    mockInterviews: [],
    governmentExams: INITIAL_GOVERNMENT_EXAMS,
    studentExamStudyPlans: [],
    studentExamSyllabusProgress: [],
    practiceQuestions: INITIAL_PRACTICE_QUESTIONS,
    mockTests: INITIAL_MOCK_TESTS,
    studentMockTestAttempts: [],
    studentResumes: [],
  };
}
